export { default as Diagnosis } from './Diagnosis.vue'
export { default as Medical } from './Medical.vue'
export { default as RoomCountdown } from './RoomCountdown.vue'
export { default as Handle } from './Handle.vue'
export { default as Disposes } from './Disposes.vue'
export { default as RoomOrder } from './RoomOrder.vue'
export { default as Illness } from './Illness.vue'
export { default as AuthorizeRecord } from './AuthorizeRecord.vue'
