export { default as Info } from './Info.vue'
export { default as History } from './History.vue'
export { default as MedicalRecord } from './MedicalRecord.vue'
export { default as Prescription } from './Prescription.vue'
export { default as Log } from './Log.vue'
export { default as DiagnosisRecord } from './DiagnosisRecord.vue'
export { default as SubmitRecord } from './SubmitRecord.vue'
